version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install GCC
          command: 'apt-get update && apt-get install -y gcc g++ wget'
      - run:
          name: Install CMake
          command: 'mkdir cmake_binary && wget --no-check-certificate --quiet -O - https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz | tar --strip-components=1 -xz -C cmake_binary ; export PATH=$(pwd)/cmake_binary/bin:$PATH'
      - run:
          name: Create build files
          command: 'mkdir build ; cd build ; cmake ..'
      - run:
          name: Versions
          command: 'g++ --version ; uname -a'
      - run:
          name: Compile
          command: 'cmake --build build'
      - run:
          name: Execute test suite
          command: 'cd build ; ctest -j 2'
